// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     PluginTsTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

import * as ui from '@grafana/schema';

/**
 * Table border style options
 */
export enum TableBorderStyle {
  None = 'none',
  Horizontal = 'horizontal',
  Vertical = 'vertical',
  All = 'all',
  Outer = 'outer',
}

/**
 * Table design preset themes
 */
export enum TableDesignPreset {
  Default = 'default',
  Minimal = 'minimal',
  Modern = 'modern',
  Striped = 'striped',
  Bordered = 'bordered',
  Elegant = 'elegant',
  Compact = 'compact',
  HighContrast = 'high-contrast',
  Glassmorphism = 'glassmorphism',
  Neon = 'neon',
  Executive = 'executive',
  Dashboard = 'dashboard',
}

/**
 * Row striping style
 */
export enum RowStripingStyle {
  None = 'none',
  Odd = 'odd',
  Even = 'even',
  Gradient = 'gradient',
}

/**
 * Header style options
 */
export enum HeaderStyle {
  Default = 'default',
  Bold = 'bold',
  Accent = 'accent',
  Gradient = 'gradient',
  Minimal = 'minimal',
  Glass = 'glass',
}

/**
 * Table styling options for appearance customization
 */
export interface TableStyling {
  /**
   * Design preset theme
   */
  designPreset?: TableDesignPreset;
  /**
   * Border style
   */
  borderStyle?: TableBorderStyle;
  /**
   * Border radius in pixels
   */
  borderRadius?: number;
  /**
   * Border color (hex or theme color)
   */
  borderColor?: string;
  /**
   * Border width in pixels
   */
  borderWidth?: number;
  /**
   * Row striping style
   */
  rowStriping?: RowStripingStyle;
  /**
   * Custom stripe color (hex or theme color)
   */
  stripeColor?: string;
  /**
   * Header style
   */
  headerStyle?: HeaderStyle;
  /**
   * Header background color
   */
  headerBgColor?: string;
  /**
   * Header text color
   */
  headerTextColor?: string;
  /**
   * Cell background color
   */
  cellBgColor?: string;
  /**
   * Cell text color
   */
  cellTextColor?: string;
  /**
   * Hover effect color
   */
  hoverColor?: string;
  /**
   * Enable hover effect
   */
  enableHoverEffect?: boolean;
  /**
   * Row divider color
   */
  rowDividerColor?: string;
  /**
   * Column divider color
   */
  columnDividerColor?: string;
  /**
   * Enable box shadow
   */
  enableShadow?: boolean;
  /**
   * Shadow intensity (0-1)
   */
  shadowIntensity?: number;
  /**
   * Enable smooth animations
   */
  enableAnimations?: boolean;
  /**
   * Font size scaling factor
   */
  fontSizeScale?: number;
  /**
   * Cell padding size
   */
  cellPadding?: 'compact' | 'normal' | 'spacious';
  /**
   * Enable column highlighting on hover
   */
  enableColumnHighlight?: boolean;
  /**
   * Enable row highlighting on hover
   */
  enableRowHighlight?: boolean;
  /**
   * Custom CSS class for table
   */
  customClass?: string;
}

/**
 * Column-specific styling options
 */
export interface ColumnStyling {
  /**
   * Column background color
   */
  backgroundColor?: string;
  /**
   * Column text color
   */
  textColor?: string;
  /**
   * Column font weight
   */
  fontWeight?: 'normal' | 'bold' | 'light';
  /**
   * Enable gradient background
   */
  gradientEnabled?: boolean;
  /**
   * Gradient start color
   */
  gradientStart?: string;
  /**
   * Gradient end color
   */
  gradientEnd?: string;
  /**
   * Highlight cells based on value thresholds
   */
  conditionalHighlight?: boolean;
}

export interface Options {
  /**
   * Controls the height of the rows
   */
  cellHeight?: ui.TableCellHeight;
  /**
   * Controls footer options
   */
  footer?: ui.TableFooterOptions;
  /**
   * Represents the index of the selected frame
   */
  frameIndex: number;
  /**
   * Controls whether the panel should show the header
   */
  showHeader: boolean;
  /**
   * Controls whether the header should show icons for the column types
   */
  showTypeIcons?: boolean;
  /**
   * Used to control row sorting
   */
  sortBy?: Array<ui.TableSortByFieldState>;
  /**
   * Table styling options
   */
  styling?: TableStyling;
}

export const defaultStyling: TableStyling = {
  designPreset: TableDesignPreset.Default,
  borderStyle: TableBorderStyle.All,
  borderRadius: 0,
  borderWidth: 1,
  rowStriping: RowStripingStyle.None,
  headerStyle: HeaderStyle.Default,
  enableHoverEffect: true,
  enableShadow: false,
  shadowIntensity: 0.1,
  enableAnimations: true,
  fontSizeScale: 1,
  cellPadding: 'normal',
  enableColumnHighlight: false,
  enableRowHighlight: true,
};

export const defaultOptions: Partial<Options> = {
  cellHeight: ui.TableCellHeight.Sm,
  footer: {
    /**
     * Controls whether the footer should be shown
     */
    show: false,
    /**
     * Controls whether the footer should show the total number of rows on Count calculation
     */
    countRows: false,
    /**
     * Represents the selected calculations
     */
    reducer: [],
  },
  frameIndex: 0,
  showHeader: true,
  showTypeIcons: false,
  sortBy: [],
  styling: defaultStyling,
};

export interface FieldConfig extends ui.TableFieldOptions {
  /**
   * Column-specific styling
   */
  columnStyling?: ColumnStyling;
}
